### ISSUE TITLE
Write specification for annotations for bindings

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#132] opened 2015-01-08 17:39 UTC
Cortex needs a piece of syntax that supports annotations. Two main use cases are:

- Documenting objects. This documentation can be taken advantage of with a future `man` command in `cxsh` as suggested by @SanderMertens. Also, the HTML generator could leverage from this.
- Overriding or disambiguating pieces of code that are hard to provide binding for, as exemplified in #131.

**Comment by SanderMertens** [comment] 2015-12-29 18:24
This is a duplicate of #169

**Closed** 2015-12-29 18:24 UTC
Labels: Corto:CodeGeneration, Corto:Documentation, Corto:Usability, enhancement
