### ISSUE TITLE
Managed strings

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#548] opened 2016-10-16 10:15 UTC
String types in Corto are value types. As such we assume that they are immutable and that every "instance" is unique and and that setting a value or calling a method will not alter strings elsewhere (except for explicit cases e.g. string objects in a hierarchy).

As such, they are always compare by content and not by identity. Value types are immutable and always copied, for example, passing

```
a="hi"
uppercase(a) // hypothetical function
a // is still "hi"
b = uppercase(a) // b is "HI" but a is "hi"
```

We can consider that the only safe and correct way to pass value types around is by making copies of them. Otherwise the "immutable" principle won't hold. As a result, every time a function that returns a Corto string is called, it must be responsibility of the caller to deallocate its memory.

Sometimes it may be desirable to have string that are not managed by the caller. Examples include:
- `corto_nameof` (although it is part of the core and not an exposed Corto function—am I wrong?)
- `/corto/web/server/request/getVar`, for performance reasons.

In order to provide a clear interface for this distinction, we can consider these two types of strings (i.e. managed by caller and managed by the function) as different types in the type system.

Core functions could have exceptions to these rules since they are only available from C.

Failure to distinguish these two types would result, in the future, in problems with memory management when using the Corto VM since the utmost VM
ioop is unable to tell whether or not it should copy a string or use the same reference, or deallocate it or not.

**Comment by SanderMertens** [comment] 2017-02-11 21:24
These are primarily questions that apply to the corto language, but since they can impact the typesystem, it is good to capture it here. Two questions are combined on one issue:

1. Who is allowed to change a string
2. Who owns the memory occupied by the string

RE: 1, I do not believe strings should always be immutable. While I see advantages (string interning) it can also lead to excessive resource allocation / deallocation which are operations that can take arbitrary amounts of time, and therefore would be unsuitable for performance-critical apps (if that is of no concern, use Python ;-).

I see no harm in eventually providing a new string type that is truly immutable, and can be interned.

However, I do believe that strings passed as function parameters should be considered immutable within the context of that function, _unless_ it is a method, and a string is the instance. In other words:
```c++
str.uppercase() // This changes 'str'
uppercase(str) // This does not change `str`
```
Since metaprocedures can be added _after_ a type is defined, users can define custom string-operations:
```c++
corto/lang/string::
    void myStringOp() metaprocedure
```

RE: 2, a similar argument applies here. If the caller always owns a string that is returned by a function, it will force resource allocations in a lot of locations where this is not strictly required. This however presents an interesting problem for the parser:
```c++
var str = obj.fullpath() // returns a new string owned by 'str'
str = obj.id() // returns a string owned by callee
// str goes out of scope, should memory be freed?
```
The issue is further complicated when `str` is assigned to another variable. Furthermore, when a value is assigned to an object (not a var), it will always have to be copied.

I see multiple solutions to this problem, which either increase complexity for the user (yet another string type) or for the parser. The parser in particular gets quite complex as we would need to:

- require [SSA](https://en.wikipedia.org/wiki/Static_single_assignment_form) to determine whether the last assigned value to a `var` is owned by the `var`
- strdup when returning a callee-owned string in a function that returns a regular string
- throw error when code returns a regular string in a function that declares to own its return value
- where do callee-owned strings come from? are they a core-only mechanism? const objects?

I lean towards solving it in the parser though, as this allows us to ignore the issue for now and allows us to build it eventually without breaking user-code.

**Comment by SanderMertens** [comment] 2017-10-04 20:32
This will be solved in the context of the corto language

**Closed by SanderMertens** 2017-10-04 20:32 UTC
